# This workflow will push and update articles on dev.to each time a new
# commit is pushed to the main branch.
#
# To make it work, you need a dev.to API key, see:
# https://developers.forem.com/api/#section/Authentication/api_key
#
# Once you have generated the token, you need to add them as a secret in your
# GitHub repository:
# - DEVTO_TOKEN: your dev.to API key
# See https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets
# for more information about GitHub secrets.

name: publish
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Use v3 of checkout for better PR handling
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # For PRs, check out the PR head
        ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || 'main' }}
        
    - name: Publish articles on dev.to
      uses: sinedied/publish-devto@v2
      id: publish_devto
      with:
        devto_key: ${{ secrets.DEVTO_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: '_devto/**/*.md'
        branch: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || 'main' }}
        conventional_commits: true
        

    # Add comment with dev.to changes if it's a pull request
    - uses: actions-ecosystem/action-create-comment@v1
      if: ${{ github.event_name == 'pull_request' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          Dev.to publishing results:
          ```
          ${{ steps.publish_devto.outputs.result_summary }}
          ```